name: CI/CD Pipeline - Debug Mode

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
      # Initial setup
      - name: Checkout code
        uses: actions/checkout@v3

      - name: System Diagnostics
        run: |
          echo "=== SYSTEM INFO ==="
          uname -a
          lsb_release -a
          echo "=== DOCKER STATUS ==="
          sudo systemctl status docker || true
          echo "=== DISK SPACE ==="
          df -h
          echo "=== DOCKER ACCESS ==="
          ls -la /var/run/docker.sock || true
          groups

      # Node.js setup
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # Build stage
      - name: Install dependencies
        working-directory: src
        run: npm ci

      - name: Run tests
        working-directory: src
        run: npm test

      # Docker operations
      - name: Docker Pre-Check
        run: |
          echo "=== BEFORE BUILD ==="
          docker ps -a
          docker images

      - name: Build Docker image
        run: |
          docker build -t local-nodejs-demoapp ./src
          docker tag local-nodejs-demoapp ${{ secrets.DOCKER_USERNAME }}/nodejs-demoapp:latest

      # Deployment
      - name: Cleanup Previous Deployment
        run: |
          docker stop nodejs-demoapp || true
          docker rm nodejs-demoapp || true
          docker network prune -f || true

      - name: Run Container with Debug
        run: |
          echo "=== STARTING CONTAINER ==="
          docker run -d \
            --name nodejs-demoapp \
            -p 3000:3000 \
            --restart unless-stopped \
            local-nodejs-demoapp
          
          echo "=== CONTAINER STATUS ==="
          docker ps -a
          
          echo "=== CONTAINER LOGS ==="
          docker logs nodejs-demoapp || true
          
          echo "=== PORT CHECK ==="
          sudo lsof -i :3000 || true
          netstat -tuln | grep 3000 || true

      # Verification
      - name: Extended Health Check
        timeout-minutes: 5
        run: |
          echo "=== HEALTH CHECK ==="
          for i in {1..30}; do
            if curl -fsS http://localhost:3000 >/dev/null; then
              echo "Application is running!"
              curl -v http://localhost:3000
              exit 0
            fi
            sleep 2
          done
          echo "=== FAILURE DIAGNOSTICS ==="
          docker inspect nodejs-demoapp
          docker logs nodejs-demoapp
          exit 1

      # Final verification
      - name: Post-Deployment Verification
        run: |
          echo "=== FINAL STATE ==="
          docker ps --format "table {{.ID}}\t{{.Names}}\t{{.Status}}\t{{.Ports}}"
          curl -v http://localhost:3000 || true
