name: CI/CD Pipeline - Port Safe

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Critical: Kill any existing process on port 3000
      - name: Free Port 3000
        run: |
          echo "=== KILLING EXISTING PROCESSES ==="
          sudo lsof -ti :3000 | xargs -r kill -9 || true
          sleep 2
          echo "=== PORT STATUS ==="
          sudo lsof -i :3000 || echo "Port 3000 is free"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: src
        run: npm ci

      - name: Build Docker image
        run: |
          docker build -t nodejs-app ./src
          docker image ls

      # Cleanup any previous containers
      - name: Remove old containers
        run: |
          docker stop nodejs-app || true
          docker rm nodejs-app || true

      # Run with health check
      - name: Deploy container
        run: |
          docker run -d \
            --name nodejs-app \
            --restart unless-stopped \
            -p 3000:3000 \
            nodejs-app
          
          echo "Waiting for startup..."
          sleep 5
          
          echo "=== CONTAINER STATUS ==="
          docker ps -a
          
          echo "=== APP LOGS ==="
          docker logs nodejs-app
          
          echo "=== PORT BINDING ==="
          docker port nodejs-app
          sudo lsof -i :3000

      # Extended verification
      - name: Verify deployment
        run: |
          echo "=== FINAL CHECKS ==="
          docker ps --format "table {{.ID}}\t{{.Names}}\t{{.Status}}\t{{.Ports}}"
          curl -v http://localhost:3000 || docker logs nodejs-app
