image:
  repository: ghcr.io/benc-uk/nodejs-demoapp
  tag: latest
  pullPolicy: Always

service:
  targetPort: 3000

secretEnv:
  WEATHER_API_KEY:
    secretName: nodejs-demoapp
    secretKey: weatherKey

env:
  AAD_APP_ID: 129e29d2-6c0a-4dbf-849e-320a3aa93d52
#   APPINSIGHTS_INSTRUMENTATIONKEY: 45f5a949-518c-4216-80bd-6c5632a9342c

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

ingress:
  enabled: true
  className: nginx
  host: nodejs-demoapp.kube.benco.io
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  tls:
    enabled: true
    secretName: benco-io-cert
